# fly.toml app configuration file generated for bpmflash on 2025-05-23T00:43:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bpmflash'
primary_region = 'otp'

[build]

[http_service]
  fly ips allocate-v4
  internal_port = 9999
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
